name: Email Step Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f1001448@ds.study.iitm.ac.in
        run: echo "Hello, world! GitHub Actions step executed."

      - name: Confirm Run
        run: echo "Workflow completed successfully."
